[build-system]
requires = ["setuptools"] 
build-backend = "setuptools.build_meta" 

[tool.setuptools]
packages = [
    "nexusrag",
    "ragatouille",
    "ragatouille.models",
    "ragatouille.data",
    "ragatouille.integrations",
    "ragatouille.negative_miners",
]

[project]
name = "nexusrag" 
version = "1.0.0"
description = "High-Performance Late-Interaction Multi-Vector Retrieval and Contextual RAG Engine by Sarthak Mun"
keywords = ["reranking", "retrieval", "rag", "nlp", "colbert", "multi-vector", "embeddings"]
authors = [
  {name = "Sarthak Mun", email = "sarthak.mun03@gmail.com" }
]
maintainers = [
  {name = "Sarthak Mun", email = "sarthak.mun03@gmail.com" }
]
license = {text = "Apache-2.0"}
readme = "README.md"

dependencies = [
  "llama-index-core",
  "faiss-cpu",
  "langchain-core",
  "langchain",
  "langchain-community",
  "colbert-ai>=0.2.19; platform_system != 'Windows'",
  "torch>=1.13",
  "transformers>=4.30.0",
  "sentence-transformers",
  "srsly",
  "onnx",
  "pydantic",
]

[project.optional-dependencies]
all = [
    "llama-index",
    "langchain",
    "rerankers",
    "voyager",
]
dev = [
    "pytest>=7.0.0",
    "ruff>=0.1.0",
    "black>=23.0.0",
]

[project.urls]
"Homepage" = "https://github.com/sarthakmun/nexusrag"
"Repository" = "https://github.com/sarthakmun/nexusrag"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::Warning"
]

target-version = "py39"
